### ISSUE TITLE
Platformer example not working

### ISSUE THREAD

**Issue by artokun** [mattjennings/react-phaser-fiber#17]
Stuck on loading screen

**Comment by mattjennings** [comment]
It appears to be working for me. Is this on CodeSandbox? If so, try clearing the local browser data for CodeSandbox. I've had issues with it caching an older version of react-phaser-fiber.

**Comment by mattjennings** [comment]
Closing this as I haven't been able to reproduce it. If you can provide a repro, I'll open it again.
