### ISSUE TITLE
Click on Text

### ISSUE THREAD

**Issue by Macklawe** [mattjennings/react-phaser-fiber#27]
how i can add event click on Text component?

**Comment by mattjennings** [comment]
I haven't gotten to event handlers via props yet (onClick etc). That'll come soon. Until then, you can get a ref to the Text component and set up an event listener as you would in Phaser normally. [Here's an example](https://codesandbox.io/s/react-phaser-fiber-onclick-example-00ylw) of how that looks.

I know it's not ideal, but this is roughly how an `onClick` listener would be implemented for GameObject components anyway, so hopefully that can get you by for now.

**Comment by mattjennings** [comment]
I've opened #28 to further the discussion on event handler support.
